services:
  - docker
 

before_install:
- docker pull crops/poky
- docker run --rm -d crops/poky --workdir=/workdir

install:
- git clone git://git.yoctoproject.org/poky

script:
- ls -alh
- pwd
- docker ps -a
