name: Build openvario image

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ warrior ]
  pull_request:
    branches: [ warrior ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Pull docker
      run: docker pull linuxianer99/ovbuild
    
    - name: Init repo
      run: repo init -u git://github.com/linuxianer99/ovlinux-manifest.git -b warrior
