name: Build openvario image

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ warrior ]
  pull_request:
    branches: [ warrior ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Pull docker
      run: docker pull linuxianer99/ovbuild
    
    - name: Show content
      run: ls -alh
    
    - name: Show dir
      run: pwd
    
    - name: Setup Sources
      run: |
        repo init -u git://github.com/linuxianer99/ovlinux-manifest.git -b warrior
        repo sync
        
    - name: Show sources
      run: |
        ls -alh
        cd poky
        ls -alh
